### ISSUE TITLE
Bot Offline?

### ISSUE THREAD

**Issue by pzerou** [GoogleFeud/codenames-bot#3]
This looks like an awesome little bot for Game Night servers under the quarantine life. 

Invited your bot, but it just shows as Offline and unresponsive. Tried commands:
-help
-tutorial
-configure

**Comment by Sellorio** [comment]
Was so excited and then so disappointed. When is this going back online or do we always have to self-host?

**Comment by volenslavchev** [comment]
Sorry for the rate reply! Why wasn't this in my recent activity? I'll be able to host the bot myself while in quarantine. Should be online in a hour or so
