### ISSUE TITLE
Game disbands abruptly + Words aren't automatically inputted

### ISSUE THREAD

**Issue by billyc618** [GoogleFeud/codenames-bot#4]
Just added the bot and we're getting these two issues:
- The bot is abruptly disbanding the game at different stages of the game. It's also been spamming the disband message. Had to kick it because of that.
![Annotation 2020-04-24 214847](https://user-images.githubusercontent.com/58643703/80268525-c0133000-8675-11ea-9992-2310f791fa31.png)
- When starting a game, the board will be blank. We've had to manually enter custom words in order for it to work.
![Annotation 2020-04-24 214407](https://user-images.githubusercontent.com/58643703/80268530-c86b6b00-8675-11ea-88bd-a79a506cf9ea.png)

**Comment by volenslavchev** [comment]
Thanks for reporting these issues! Is the board always blank or does it happen sometimes? 

EDIT: Just tried it and yes it is always blank. Will look into it asap.

**Comment by volenslavchev** [comment]
Both issues should be fixed. When the game starts, the random words pulled from the list of words were deleted, this shouldn't be the case anymore. Now game gets disbanded when there hasn't been any activity (giving clues, guessing) in over 20 minutes.

Again, thanks for reporting! I wouldn't have caught those if you didn't tell me!

**Comment by billyc618** [comment]
Thanks!
