### ISSUE TITLE
Bot Not Responding, But Online

### ISSUE THREAD

**Issue by CallMeMrCulture** [GoogleFeud/codenames-bot#5]
Hey there! I was just curious if there is something I am missing about getting the bot set up for my server, or if the bot is just not working in general. I have tried -help, -tutorial, and -configure, but the bot is unresponsive with all of them. Thank you!

**Comment by volenslavchev** [comment]
I'm sorry for the very late response - for some reason I am not getting notifications for this repository. The bot should always respond to the commands you mentioned, is the error still occuring? Maybe it doesn't have permission to send message?
