### ISSUE TITLE
Bot offline

### ISSUE THREAD

**Issue by HondSchaap** [GoogleFeud/codenames-bot#7]
Trying to invite the bot to my server using the invite link in the description, but after inviting, the bot appears offline and is unresponsive to commands.

**Comment by volenslavchev** [comment]
Bot is going to be offline for a while, I don't have the resources to continue hosting it, apologies! You can try hosting it yourself if you have a VPS available, alternatively you can try with websites like glitch.com. 

If you need help with setting it up, contact me on discord, I'd be happy to help! GoogleFeud#5048

**Comment by volenslavchev** [comment]
Update: I'm rewriting the bot, expect the official [instance of the bot](https://top.gg/bot/606487052992905247) to be online later this month / next month!
